name: fake_reflection
description: A package to get a class structure (like reflection) in runtime without code generation.
version: 1.0.1
homepage: https://github.com/davidsdearaujo/fake_reflection

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  test: '>=1.21.4'
  lints: '>=2.0.0'
